### ISSUE TITLE
Need better unit test coverage in many packages

### ISSUE THREAD

**Issue by gh0stwheel** [oscoin/osrank-java#1]

**Comment by gh0stwheel** [comment]
I did some work on this this week. A few more tests are still needed, especially related to FileGraphLoader and io.oscoin.algo* classes.

**Comment by ankurdelight** [comment]
still need tests for:

* FileGraphLoader
* OutputUtils
* OsrankParams
* OsrankResults
* NaiveRun

**Comment by ankurdelight** [comment]
FileGraphLoader (ankur)
OutputUtils (ankur) 
OsrankParams (ankur)
OsrankResults (andrew)
NaiveRun (andrew)
