### ISSUE TITLE
README should have instructions for running maven with no IDE

### ISSUE THREAD

**Issue by gh0stwheel** [oscoin/osrank-java#4]

**Comment by ankurdelight** [comment]
@andrewpdickson Somewhat related I just pushed notes to the README about how to generate a jar from Intellij, and run that jar from the commandline.

**Comment by gh0stwheel** [comment]
@ankurdelight -- nice!

I'm going to close this one out for now. We can re-open if we end up with people asking about building using Maven, but for now if anyone wants to run from the command line we can just build a jar and let them use that to run.
