### ISSUE TITLE
Readme should include instructions about how to run some of the Osrank app classes

### ISSUE THREAD

**Issue by gh0stwheel** [oscoin/osrank-java#6]

**Comment by ankurdelight** [comment]
@andrewpdickson how is this different than issue #4 that we just addressed?

**Comment by gh0stwheel** [comment]
@ankurdelight my thought was to provide instructions about how to setup and run app classes in intelliJ

**Comment by ankurdelight** [comment]
Got it
 Thanks

sent from small radiation device. don't panic!

**Comment by gh0stwheel** [comment]
This is done.
